CREATE TABLE "registrations" (
	"id" serial PRIMARY KEY NOT NULL,
	"team_name" varchar(100) NOT NULL,
	"leader_name" varchar(100) NOT NULL,
	"leader_whatsapp" varchar(20) NOT NULL,
	"player1_name" varchar(100) NOT NULL,
	"player1_ml_id" varchar(50) NOT NULL,
	"player1_server" varchar(50) NOT NULL,
	"player2_name" varchar(100) NOT NULL,
	"player2_ml_id" varchar(50) NOT NULL,
	"player2_server" varchar(50) NOT NULL,
	"player3_name" varchar(100) NOT NULL,
	"player3_ml_id" varchar(50) NOT NULL,
	"player3_server" varchar(50) NOT NULL,
	"player4_name" varchar(100) NOT NULL,
	"player4_ml_id" varchar(50) NOT NULL,
	"player4_server" varchar(50) NOT NULL,
	"player5_name" varchar(100) NOT NULL,
	"player5_ml_id" varchar(50) NOT NULL,
	"player5_server" varchar(50) NOT NULL,
	"sub1_name" varchar(100),
	"sub1_ml_id" varchar(50),
	"sub1_server" varchar(50),
	"sub2_name" varchar(100),
	"sub2_ml_id" varchar(50),
	"sub2_server" varchar(50),
	"slot" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
